---
title: "Conditional Statements, Loops and Functions in R"
author: "Brian Schetzsle"
output: 
  xaringan::moon_reader:
    css: ["slide-style.css", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"]
    lib_dir: libs
    seal: false
    nature:
      beforeInit: "cols_macro.js"
      ratio: 16:9
      highlightStyle: "pygments"
      highlightLines: true
      highlightLanguage: "r"

---

class: title-slide

```{r echo = FALSE, message=FALSE}
library(openintro)
library(tidyverse)
babies <- babies %>% 
  mutate(smoke = as.logical(smoke),
         parity = as.logical(parity))

xaringanExtra::use_panelset()
theme_set(theme_gray(base_size = 18))
```

<br>
<br>
.right-panel[ 
<br>

# `r rmarkdown::metadata$title`
## `r rmarkdown::metadata$author`

]

---

class: middle

## Reminder

- Close all apps on your computer other than zoom.  
- Open slides for this session from the cluster website (https://uci-dshs.netlify.app/). 
- We will be working with the capstone project [data](https://github.com/COSMOS-DataScience/slides/blob/main/data/alzheimer_data.csv).

---

## Conditional Statements in R

```{r eval = FALSE}
if(condition){
  print("Fantastic!")
} else {
  print("OOPS!")
}
```

```{r eval = FALSE}
ifelse(condition, yes = "Fantastic!", no = "OOPS!" )
```

```{r eval = FALSE}
case_when(
  condition ~ "Fantastic!",
  TRUE ~ "OOPS!"
)
```

---

## Loops

```{r eval = FALSE}
for(i in 1:10){
  print(i)
}
```

```{r eval = FALSE}
i <- 1
while(i <= 10){
  print(i)
  i <- i + 1
}
```

```{r eval = FALSE}
apply(data, MARGIN = 2, FUN = mean)
```

---

## Creating Functions

```{r eval = FALSE}
my_function <- function(input){
  if(input == TRUE){
    return("Fantastic!")
  }
  else{
    return("OOPS!")
  }
}
```
